(define (problem pb1)
    	(:domain monkeyUpDown)
  	(:objects p1 p2 p3 bananas monkey box knife)
  	(:init (location p1)
		(location p2)
		(location p3)
	 	(at monkey p1)
		(on-floor)
		(at box p2)
		(at bananas p3)
	 	(at knife p2)
	 	;; blow and P0TRAN are implicitly set to false
	)	
  	(:goal (and (hasbananas)))
)